#!/bin/bash
#
# Startup script for the PHP-FPM server.
#
# chkconfig: 345 85 15
# description: PHP is an HTML-embedded scripting language
# processname: php-fpm
# config: /usr/local/php/etc/php.ini
 
# Source function library.
#. /etc/rc.d/init.d/functions
 
PHP_PATH=/data
DESC="php-fpm daemon"
NAME=php-fpm
# php-fpm 路径
DAEMON=$PHP_PATH/php5.4/sbin/$NAME
# 配置文件
CONFIGFILE=$PHP_PATH/php5.4/etc/php-fpm.conf
# PID路径
#PIDFILE=$PHP_PATH/php5.4/var/run/$NAME.pid
PIDFILE=/tmp/$NAME.pid
INI_CONF=$PHP_PATH/php5.4/etc/php.ini


SCRIPTNAME=/etc/init.d/$NAME
 
# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0
 
rh_start() {
  $DAEMON -y $CONFIGFILE -c $INI_CONF || echo -n " already running"
}
 
rh_stop() {
  kill -QUIT `cat $PIDFILE` || echo -n " not running"
}
 
rh_reload() {
  kill -HUP `cat $PIDFILE` || echo -n " can't reload"
}
 
case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        rh_start
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        rh_stop
        echo "."
        ;;
  reload)
        echo -n "Reloading $DESC configuration..."
        rh_reload
        echo "reloaded."
  ;;
  restart)
        echo -n "Restarting $DESC: $NAME"
        rh_stop
        sleep 1
        rh_start
        echo "."
        ;;
  *)
         echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
         exit 3
        ;;
esac
exit 0

